# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/hssl_ctrl_fifo_1x/hssl_ctrl_fifo_1x.xci
# IP: The module: 'hssl_ctrl_fifo_1x' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/hssl_ctrl_fifo_1x/hssl_ctrl_fifo_1x.xdc
# XDC: The top module name and the constraint reference have the same name: 'hssl_ctrl_fifo_1x'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/hssl_ctrl_fifo_1x/hssl_ctrl_fifo_1x_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hssl_ctrl_fifo_1x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/hssl_ctrl_fifo_1x/hssl_ctrl_fifo_1x_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hssl_ctrl_fifo_1x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/hssl_ctrl_fifo_1x/hssl_ctrl_fifo_1x.xci
# IP: The module: 'hssl_ctrl_fifo_1x' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/hssl_ctrl_fifo_1x/hssl_ctrl_fifo_1x.xdc
# XDC: The top module name and the constraint reference have the same name: 'hssl_ctrl_fifo_1x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/hssl_ctrl_fifo_1x/hssl_ctrl_fifo_1x_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hssl_ctrl_fifo_1x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/hssl_ctrl_fifo_1x/hssl_ctrl_fifo_1x_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hssl_ctrl_fifo_1x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
