# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/aurora/aurora.xci
# IP: The module: 'aurora' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/aurora/aurora_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/aurora/aurora.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/aurora/aurora_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/aurora/aurora.xci
# IP: The module: 'aurora' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/aurora/aurora_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/aurora/aurora.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/work/SFP-Simulation-link/source/hdl/vhdl/VC707/coregen/ip/aurora/aurora_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
